CSV_DELIMITER = ";"
REQUESTS_TIMEOUT = 120
IMAGE_TIMEOUT = 50
BATCH_SIZE = 1000
DEFAULT_PRODUCT_TYPE = "product"
STATE_AVAILABLE = "disponible"
SECOND_HAND_SUFFIX = "OKA"
SECOND_HAND_DEFAULT_CODE = "Segunda Mano"
